#config_version=6

mode:
    start_events: player_letter_count{value>=15}, ball_started{player_letter_count>=15}
    stop_events: ball_will_end, sq_extra_ball_hit
    priority: 102

extra_balls:
    my_mode_eb:
        award_events: sq_extra_ball_hit

variable_player:
    sq_extra_ball_hit:
        letter_count:
          int: 0
          action: set
# collect bonus - this needs to move elsewhere
        score: 15*10000*bonus_multiplier

show_player:
    mode_extra_ball_started: 
        eb_letter_show:
          action: play
    mode_extra_ball_stopped:
        eb_letter_show:
          action: stop
# variable_player:

# sequence_shots:
   
# slide_player:
#  sq_left_orbit_combo_hit:
#    widgets:
#      - type: text
#        text: COMBO!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_left_drain_combo:
#    widgets:
#      - type: text
#        text: COMBO!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_right_drain_combo:
#    widgets:
#      - type: text
#        text: COMBO!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_left_right_shatz_hit:
#    widgets:
#      - type: text
#        text: shatz!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_right_left_shatz_hit:
#    widgets:
#      - type: text
#        text: shatz!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
