#config_version=5

mode:
    start_events: shot_double_scoring_loop_hit
    stop_events: ball_will_end, timer_mode_timer_complete
    priority: 103

timers:
  double_scoring_timer:
    start_value: 0
    end_value: 20
    control_events:
      - action: start
        event: mode_your_mode_started

variable_player:
    mode_double_scoring_started:
        multiplier:
          int: 2
          action: set

# show_player:
#    mode_extra_ball_started: 
#        eb_letter_show:
#          action: play
#    mode_extra_ball_stopped:
#        eb_letter_show:
#          action: stop
# variable_player:

# sequence_shots:
   
# slide_player:
#  sq_left_orbit_combo_hit:
#    widgets:
#      - type: text
#        text: COMBO!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_left_drain_combo:
#    widgets:
#      - type: text
#        text: COMBO!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_right_drain_combo:
#    widgets:
#      - type: text
#        text: COMBO!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_left_right_shatz_hit:
#    widgets:
#      - type: text
#        text: shatz!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
#  sq_right_left_shatz_hit:
#    widgets:
#      - type: text
#        text: shatz!!!
#        number_grouping: true
#        min_digits: 2
#        font_size: 300
#        font_name: VCR OSD
#        anchor_y: top
#    expire: 2s
